repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: ["--exclude", "*_test.py,test_utils.py"]
      - id: ruff-format
        args: ["--exclude", "*_test.py,test_utils.py"]