sudo: false

language: python

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
    - python: nightly
      dist: trusty
      sudo: false
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements.txt

before_script:
  - flake8

script:
- make -j8 OPTS='-v' test
