sudo: false

language: python

matrix:
  include:
    - python: 3.8
      dist: bionic
      sudo: true

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-nl

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  # - ./lint.sh
  - ./test.sh
  - codecov

after_success:
  - coveralls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
