sudo: false

language: python

matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true
    - python: 3.8
      dist: bionic
      sudo: true
  allow_failures:
    - python: 3.8

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  # - ./lint.sh
  - travis_wait 1000 ./test.sh
  - codecov

after_success:
  - coveralls
