name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        python-version: '3.7'
    - name: Run tests
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest pytest-cov
        ./test.sh
