name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Run tests
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest pytest-cov
        ./test.sh

  repo-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Check config
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install "sp-repo-review[cli]"
        repo-review .
