name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Run tests
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest pytest-cov
        ./test.sh

  action:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run repo-review action
        uses: ./
        with:
          plugins: sp-repo-review==2023.12.21