name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Run tests
      run: |
        sudo apt-get install python3-setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest pytest-cov
        ./test.sh

  repo-review:
    name: Repo review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      id: python
      with:
        python-version: "3.11"
        update-environment: false

    - name: Run repo-review
      shell: bash
      run: >
        pipx run
        --python '${{ steps.python.outputs.python-path }}'
        repo-review .
        --format html
        --stderr rich
        >> $GITHUB_STEP_SUMMARY
